language: php

php:
 - 7.2
 - 7.3

before_script:
# - pecl install channel://pecl.php.net/pthreads-3.1.6
 - echo | pecl install channel://pecl.php.net/yaml-2.0.2
 - pecl install channel://pecl.php.net/crypto-0.3.1
 - git clone https://github.com/pmmp/pthreads.git
 - cd pthreads
 - git checkout 1c30bca314dc0fa7aa159d06b04f49fbd05c332f
 - phpize
 - ./configure
 - make
 - make install
 - cd ..
 - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - composer install

script:
 - ./tests/travis.sh -t4

notifications:
 email: false
